//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.01 at 03:57:52 PM EST 
//


package gov.nist.healthcare.cds.domain.xml.beans;

import javax.xml.bind.annotation.*;

import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="RELATIVE"/>
 *               &lt;enumeration value="FIXED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MetaData" type="{https://fits.nist.gov/xml/}MetaDataType"/>
 *         &lt;element name="AssessmentDate" type="{https://fits.nist.gov/xml/}DateType"/>
 *         &lt;element name="Patient" type="{https://fits.nist.gov/xml/}PatientType"/>
 *         &lt;element name="Events" type="{https://fits.nist.gov/xml/}EventsType" minOccurs="0"/>
 *         &lt;element name="Forecasts" type="{https://fits.nist.gov/xml/}ForecastsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="UID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "name",
        "description",
        "group",
        "dateType",
        "metaData",
        "assessmentDate",
        "patient",
        "events",
        "forecasts",
        "forecastType",
        "evaluationType",
        "workflowTag",
        "tags",
})
@XmlRootElement(name = "TestCase")
public class TestCase {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Group")
    protected String group;
    @XmlElement(name = "DateType", required = true)
    protected String dateType;
    @XmlElement(name = "MetaData", required = true)
    protected MetaDataType metaData;
    @XmlElement(name = "AssessmentDate", required = true)
    protected DateType assessmentDate;
    @XmlElement(name = "Patient", required = true)
    protected PatientType patient;
    @XmlElement(name = "Events")
    protected EventsType events;
    @XmlElement(name = "Forecasts")
    protected ForecastsType forecasts;
    @XmlAttribute(name = "UID")
    protected String uid;
    @XmlElement(name = "ForecastType")
    protected String forecastType;
    @XmlElement(name = "EvaluationType")
    protected String evaluationType;
    @XmlElement(name = "WorkflowTag")
    protected String workflowTag;
    @XmlElementWrapper(name = "Tags")
    @XmlElement(name = "Tag")
    protected List<String> tags;


    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the group property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the dateType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * Sets the value of the dateType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateType(String value) {
        this.dateType = value;
    }

    /**
     * Gets the value of the metaData property.
     *
     * @return
     *     possible object is
     *     {@link MetaDataType }
     *
     */
    public MetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     *
     * @param value
     *     allowed object is
     *     {@link MetaDataType }
     *
     */
    public void setMetaData(MetaDataType value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the assessmentDate property.
     *
     * @return
     *     possible object is
     *     {@link DateType }
     *
     */
    public DateType getAssessmentDate() {
        return assessmentDate;
    }

    /**
     * Sets the value of the assessmentDate property.
     *
     * @param value
     *     allowed object is
     *     {@link DateType }
     *
     */
    public void setAssessmentDate(DateType value) {
        this.assessmentDate = value;
    }

    /**
     * Gets the value of the patient property.
     *
     * @return
     *     possible object is
     *     {@link PatientType }
     *
     */
    public PatientType getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     *
     * @param value
     *     allowed object is
     *     {@link PatientType }
     *
     */
    public void setPatient(PatientType value) {
        this.patient = value;
    }

    /**
     * Gets the value of the events property.
     *
     * @return
     *     possible object is
     *     {@link EventsType }
     *
     */
    public EventsType getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     *
     * @param value
     *     allowed object is
     *     {@link EventsType }
     *
     */
    public void setEvents(EventsType value) {
        this.events = value;
    }

    /**
     * Gets the value of the forecasts property.
     *
     * @return
     *     possible object is
     *     {@link ForecastsType }
     *
     */
    public ForecastsType getForecasts() {
        return forecasts;
    }

    /**
     * Sets the value of the forecasts property.
     *
     * @param value
     *     allowed object is
     *     {@link ForecastsType }
     *
     */
    public void setForecasts(ForecastsType value) {
        this.forecasts = value;
    }

    /**
     * Gets the value of the uid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUID(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the workflow tag property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *     possible values are
     *     - Suggested
     *     - Deleted
     *     - On hold
     *     - Final
     *
     */
    public String getWorkflowTag() {
        return workflowTag;
    }

    /**
     * Sets the value of the workflow-tag property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *     allowed values are
     *     - Suggested
     *     - Deleted
     *     - On hold
     *     - Final
     *
     */
    public void setWorkflowTag(String value) {
        this.workflowTag = value;
    }

    /**
     * Gets the value of the Tags property.
     *
     * @return
     *     possible object is
     *     {@link List<String> }
     *
     */
    public List<String> getTags() {
        return tags;
    }

    /**
     * Sets the value of the Tags property.
     *
     * @return
     *     allowed object is
     *     {@link List<String> }
     *
     */
    public void setTags(List<String> values) {
        this.tags = values;
    }

    /**
     * Gets the value of the forecastType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getForecastType() {
        return forecastType;
    }


    /**
     * Sets the value of the forecastType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setForecastType(String value) {
        this.forecastType = value;
    }


    /**
     * Gets the value of the evaluationType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEvaluationType() {
        return evaluationType;
    }

    /**
     * Sets the value of the evaluationType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEvaluationType(String value) {
        this.evaluationType = value;
    }
}
